version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: my-laravel-app
        container_name: my-laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network

    node:
        image: node:latest
        volumes:
            - ./:/var/www
        working_dir: /var/www
        command: sh -c "npm install && npm run hot"
        ports:
            - "8080:8080"
        networks:
            - app-network
        environment:
            - CHOKIDAR_USEPOLLING=true
            - CHOKIDAR_INTERVAL=1000

    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        ports:
            - "8090:80"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
